### ISSUE TITLE
Exception when parsing

### ISSUE THREAD

**Issue by jmdavid** [gdsestimating/dxf-parser#7]
I integrated the parser in a node.js app and I get this error on a fairly complex cad:

Error: Expected code for point value to be 50 but got 41.
    at parsePoint (.\dev\dxf-parser\tools\dxf-parser.js:1217:11)
    at parsePolylinePoints (.\dev\dxf-parser\tools\dxf-parser.js:1236:13)
    at parseLWPOLYLINE (.\dev\dxf-parser\tools\dxf-parser.js:1443:24)
    at parseEntities (.\dev\dxf-parser\tools\dxf-parser.js:987:15)
    at parseBlock (.\dev\dxf-parser\tools\dxf-parser.js:621:23)
    at parseBlocks (.\dev\dxf-parser\tools\dxf-parser.js:552:13)
    at parseAll (.\dev\dxf-parser\tools\dxf-parser.js:470:19)
    at DxfParser._parse (.\dev\dxf-parser\tools\dxf-parser.js:1735:2)
    at ReadStream.onEnd (.\dev\dxf-parser\tools\dxf-parser.js:432:19)
   ...

**Comment by bzuillsmith** [comment]
Ok, I probably wrote this to expect coordinates values to come in a specific order. It's possible the Acad spec is more lenient than that though. Won't be able to get to this immediately. Feel free to do a pull request though.

**Comment by bzuillsmith** [comment]
Can you give me the file for testing? Or perhaps one that reproduces the error?

**Comment by jmdavid** [comment]
Please download from dropbox :

 

https://www.dropbox.com/sh/rc7dohbtfp6yiy7/AABrWC1ECKieUAAucQzwez8Ha?dl=0

**Comment by bzuillsmith** [comment]
Thanks for the file. It was very helpful in figuring out the issue. The fix has been publish as version 0.4.1.
